### PR TITLE
added failing tests for internationalized domain names

### PR DESCRIPTION
**Pull request by dg**

### CODE REVIEW

**Comment by dominicsayers** [comment]
Thanks for this PR, @dg 

The reason for `is_email()` to exist is to check the validity of an email address according to the RFCs, particularly RFC 5321 and RFC 5322. Whether this is useful for an application is immaterial - that's what `is_email()` does :-)

The RFCs say the tests you've provided should fail because those characters are not allowed in domain names. Here are some references:

```
domain          =   dot-atom / domain-literal / obs-domain
```
(http://tools.ietf.org/html/rfc5322#section-3.4.1)

```
   atext           =   ALPHA / DIGIT /    ; Printable US-ASCII
                       "!" / "#" /        ;  characters not including
                       "$" / "%" /        ;  specials.  Used for atoms.
                       "&" / "'" /
                       "*" / "+" /
                       "-" / "/" /
                       "=" / "?" /
                       "^" / "_" /
                       "`" / "{" /
                       "|" / "}" /
                       "~"

   atom            =   [CFWS] 1*atext [CFWS]

   dot-atom-text   =   1*atext *("." 1*atext)

   dot-atom        =   [CFWS] dot-atom-text [CFWS]
```
(http://tools.ietf.org/html/rfc5322#section-3.2.3)

Now, back in the real world, the address you included in test 169 works just fine. There could be two reasons for this:

1.  The internationalized domain could be translated into punycode before it's interpreted by the Message Transfer Agent. This guarantees that the domain contains only `atext` characters, or
1.  The Message Transfer Agent has no problem with the international characters in the domain because it can handle UTF-8 (or equivalent). In this case it delivers the email correctly because it is acting in accordance with the Robustness Principle (https://en.wikipedia.org/wiki/Robustness_principle) - in other words: deliver the email if you can regardless of it's comformance with the RFCs.

Regarding punycode, it is not the job of the validator itself to perform this transformation. That would either complicate the code or add a library dependency. It's easy enough for an app to do this transformation before presenting the email address to the validator.

For a real-world app you probably want to know if a user's email address is useful or not, rather than whether it conforms strictly with the RFCs. `is_email()` is part of this checking not the whole of it. `is_email()` will tell you if the email address conforms with the RFCs, it doesn't tell you whether you should accept it in your app or not. If the user insists that's her email then you should probably accept it regardless of conformance but you could use `is_email()` to warn her that it's unusual in some way.

More here: http://isemail.info/about

So I appreciate the effort you've put into making the PR but I don't agree that these tests should respond as you suggest.

**Comment by dominicsayers** [comment]
Also, see tests 100 and 101

**Comment by dg** [comment]
Perhaps it should be mentioned in the documentation that punycode filter should be used before the validator to make it work in the way users probably expect.

**Comment by dominicsayers** [comment]
Good call, @dg. Very happy to accept a PR that explains it in a way that makes sense to you. Maybe a better README? Feel free to use any of my text here or from http://isemail.info.

**Pull request closed without merging**
